### ISSUE TITLE
cannot load io/fs: malformed module path "io/fs": missing dot in first path element

### ISSUE THREAD

**Issue by wajika** [segmentio/kubectl-curl#7]
ubuntu 20.04 
go version go1.13.8 linux/amd64

`go get github.com/segmentio/kubectl-curl@latest`
`build github.com/segmentio/kubectl-curl: cannot load io/fs: malformed module path "io/fs": missing dot in first path element`

**Comment by achille-roussel** [comment]
Hello @wajika 

I believe you need a Go version which had the `io/fs` package avaialble, Go 1.13 did not, which is why compilation is breaking.

The program was built with Go 1.17, so using 1.17 or 1.18 should resolve the issue.
